// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMILO-OngKLvZgSNysJU8Iz_UeaUz61dY',
    appId: '1:739170789151:web:4c65e1216e003139a1b22a',
    messagingSenderId: '739170789151',
    projectId: 'dartslinkprojectdevelop',
    authDomain: 'dartslinkprojectdevelop.firebaseapp.com',
    storageBucket: 'dartslinkprojectdevelop.appspot.com',
    measurementId: 'G-BM7L49QFZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiMR5MiuwoDqbVc5TXxCFjW34ITEkgQcU',
    appId: '1:739170789151:android:c605d207ec0daf39a1b22a',
    messagingSenderId: '739170789151',
    projectId: 'dartslinkprojectdevelop',
    storageBucket: 'dartslinkprojectdevelop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnFsD02KUyQdjaYAtrbTFn2P4eKXrIwjY',
    appId: '1:739170789151:ios:7a97b6996b7a3814a1b22a',
    messagingSenderId: '739170789151',
    projectId: 'dartslinkprojectdevelop',
    storageBucket: 'dartslinkprojectdevelop.appspot.com',
    iosClientId: '739170789151-9ndh1ks85gs55f2ad99jo5ad6a48nbrj.apps.googleusercontent.com',
    iosBundleId: 'com.darts.link.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnFsD02KUyQdjaYAtrbTFn2P4eKXrIwjY',
    appId: '1:739170789151:ios:25c80f777b2ab326a1b22a',
    messagingSenderId: '739170789151',
    projectId: 'dartslinkprojectdevelop',
    storageBucket: 'dartslinkprojectdevelop.appspot.com',
    iosClientId: '739170789151-0ppjl0k5ouq9b4s4h23d7lvsts9m85pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartsLinkProject',
  );
}
